Switch to newer avail-core.
maticnetwork/avail pull request #120
Opened 2022-11-25 12:34 UTC by luka-ethernal

2022-11-25 12:46 UTC, MiguelDD1 requested changes
Please merge into `develop` branch.

2022-11-25 12:46 UTC, MiguelDD1 commented on Cargo.lock
> +version = "0.4.0"
Should not `da-primitives` be also `0.5.0` following the tag?

2022-11-28 06:38 UTC, aterentic-ethernal commented on pallets/system/src/limits.rs
> +			rows: MAX_BLOCK_ROWS.0,
This was a bug?

2022-11-28 14:59 UTC, luka-ethernal commented on pallets/system/src/limits.rs
> +			rows: MAX_BLOCK_ROWS.0,
I guess so. I changed it along the way.

2022-12-02 10:06 UTC, closed without merging