Add data root field inside header extrinsic root
maticnetwork/avail pull request #74
Opened 2022-08-31 13:59 UTC by prabal-banerjee

2022-08-31 20:18 UTC, aterentic-ethernal commented on pallets/system/src/header_builder.rs
> +pub struct AvailExtrinsic {
Maybe it makes sense to move this struct to da-primitives and reuse it in both header builder and rpc call?

2022-08-31 20:57 UTC, aterentic-ethernal approved these changes
Looks good to me, just formatting and if its possible, we should reuse structs.

2022-09-01 07:35 UTC, aterentic-ethernal requested changes
There is also a test in runtime/src/lib.rs which fails to compile, so changes has to be made before merge

2022-09-01 08:01 UTC, kroos47 commented
> There is also a test in runtime/src/lib.rs which fails to compile, so changes has to be made before merge

yeh actually multiple other tests needs to be fixed, so working on it. 😄

2022-09-07 07:55 UTC, kroos47 approved these changes

2022-09-07 07:55 UTC, merged